### ISSUE TITLE
Logging format in R packages

### ISSUE THREAD

**Issue by corey-dawson** [daroczig/logger#118]
I want to use this logging solution inside a package I am building. I am seeing an issue where the package is not using the format I've specified, after I build and install the package. See sample below:

```
# setup logger
# ==========================================================================
pkglog <- logger::layout_glue_generator(format = '{time} | {level} | mypkg | {sys.call(1)[[1]]} | {msg}')
logger::log_layout(pkglog, namespace = 'pkg')
logger::log_threshold(logger::INFO, namespace = 'pkg')

#' function to decode base64 encoded strings
#' @param encoded_str base84 encoded string to decode
#' @return decoded string
#' @keywords internal
#' @examples
#' mypass <- decode(encoded_str = "bXlwYXNzCg==")
#' @export
decode <- function(encoded_str){
  decoded <- trimws(rawToChar(openssl::base64_decode(encoded_str)))
  logger::log_info("Decoded", namespace="pkg")
  return(decoded)
}
```

![image](https://github.com/daroczig/logger/assets/79542680/4f0e22db-aafb-442b-ac17-014b3fb61481)

If I create this function ad-hoc (not within a package) with same format, I get the desired output

![image](https://github.com/daroczig/logger/assets/79542680/ec1ca535-f9ec-4ee1-9655-1e78aa372eec)

Any direction would be helpful. thanks in advance.

**Comment by daroczig** [comment]
You don't necessarily need to set the `namespace` inside of a package: it will be the package name itself by default -- but of course you should be able to set that to something custom if needed.

Not sure what is wrong there, it should work, and it worked in a minimal reproducible example I set up locally. Can you try importing `log_info` instead of the double-colon approach?

If you can share your repo, I'm happy to take a closer look.

**Comment by daroczig** [comment]
Please reopen with more info as per above.
