### ISSUE TITLE
logger cannot be used in `reprex::reprex()`

### ISSUE THREAD

**Issue by DanChaltiel** [daroczig/logger#127]
Hi,

It seems that logger cannot be used in `reprex::reprex()`.

For example, here is a manual reprex from copypasting my console :
``` r
logger::log_warn("foobar")
# WARN [2023-10-22 16:52:16] foobar
```

<sup>Created on 2023-10-22 with my own hands</sup>

While here is the same example using `reprex::reprex()` (no output): 
``` r
logger::log_warn("foobar")
```

<sup>Created on 2023-10-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I have no idea if this is related, but it seems that `reprex::reprex()` is not allowing the use of `globalCallingHandlers()`:
``` r
logger::log_warnings()
#> Error in globalCallingHandlers(warning = function(m) {: should not be called with handlers on the stack
```

<sup>Created on 2023-10-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by daroczig** [comment]
Thanks for reporting this!

I think this is due to `reprex` not showing the `stderr` that is used by default for logging, but when setting that to `stdout` as part of the `reprex`, it shows up, see e.g.:

``` r
library(logger);log_appender(appender_stdout); log_info(42)
#> INFO [2023-10-23 23:25:06] 42
```

<sup>Created on 2023-10-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Another option might be to use the `std_out_err` option of `reprex`, resulting in:

``` r
logger::log_info(42)
```

<sup>Created on 2023-10-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Standard output and standard error
</summary>

``` sh
INFO [2023-10-23 23:26:20] 42
```

</details>

**Comment by DanChaltiel** [comment]
Nice!

It seems you are not using [issues templates](https://github.com/DanChaltiel/crosstable/blob/main/.github/ISSUE_TEMPLATE/bug_report.md?plain=1), but if this solves the problem maybe you could put this in a Bug issue template?

Something like:
> Please include a reprex using `reprex::reprex(std_out_err=...)`

**Comment by daroczig** [comment]
great idea, thanks!
