### ISSUE TITLE
relicense from AGPL to MIT

### ISSUE THREAD

**Issue by daroczig** [daroczig/logger#172]
Although I thought (10+ years ago) that AGPL-3 effectively addressed the potential issue of SaaS companies taking advantage of open-source software without contributing back, the licensing terms seem to be confusing and interpreted differently by orgs and lawyers. Given the multiple requests from the past years I've received to relicense to a more permissive license, and my current belief that `logger` does not benefit from the restrictions of AGPL -- I am hereby starting the relicensing process to MIT.

To do so, I need approval from all copyright holders ([past contributors](https://github.com/daroczig/logger/graphs/contributors)):

- [x] @Polkas
- [x] @hadley 
- [x] @philaris 
- [x] @amy17519 
- [x] @deeenes 
- [x] @MichaelChirico 
- [x] @artemklevtsov 
- [x] @stPhena 
- [x] @earino 
- [x] @averissimo 
- [x] @jozefhajnala 
- [x] @atheriel 
- [x] @pawelru 
- [x] @aaelony 
- [x] @terashim 
- [x] @DanChaltiel 
- [x] @burgikukac 
- [x] @kpagacz 
- [x] @tdeenes 

I know this is painful and boring, but the relicensing can only happen if I get acceptance from everyone, so **please kindly reply below** stating:

> I accept the change of logger's license to MIT.

Otherwise, please feel free to let me know your concerns, questions etc.

Thanks for your past contributions and your help in this process as well!

**Comment by MichaelChirico** [comment]
I accept the change of logger's license to MIT.

Thank you for this, I can attest that google has a by-strict-exception-only policy for AGPL third party code: https://opensource.google/documentation/reference/using/agpl-policy

**Comment by burgikukac** [comment]
I accept the change of logger's license to MIT.

**Comment by tdeenes** [comment]
I accept the change of logger's license to MIT.

**Comment by aaelony** [comment]
I accept the change of logger's license to MIT.On Aug 4, 2024, at 15:29, Gergely Daróczi ***@***.***> wrote:﻿
Although I thought (10+ years ago) that AGPL-3 effectively addressed the potential issue of SaaS companies taking advantage of open-source software without contributing back, the licensing terms seem to be confusing and interpreted differently by orgs and lawyers. Given the multiple requests from the past years I've received to relicense to a more permissive license, and my current belief that logger does not benefit from the restrictions of AGPL -- I am hereby starting the relicensing process to MIT.
To do so, I need approval from all copyright holders (past contributors):

 @Polkas
 @hadley
 @philaris
 @amy17519
 @deeenes
 @MichaelChirico
 @artemklevtsov
 @stPhena
 @earino
 @averissimo
 @jozefhajnala
 @atheriel
 @pawelru
 @aaelony
 @terashim
 @DanChaltiel
 @burgikukac
 @kpagacz
 @tdeenes

I know this is painful and boring, but the relicensing can only happen if I get acceptance from everyone, so please kindly reply below stating:

I accept the change of logger's license to MIT.

Otherwise, please feel free to let me know your concerns, questions etc.
Thanks for your past contributions and your help in this process as well!

**Comment by atheriel** [comment]
I accept the change of logger's license to MIT.

In the past I've cited the AGPL as a reason to avoid this package for corporate Shiny apps, so happy to see it change. R community norms are strongly in favour of folks contributing back regardless of license, too.

**Comment by hadley** [comment]
Approved!

**Comment by DanChaltiel** [comment]
I accept the change of logger's license to MIT.

**Comment by pawelru** [comment]
I accept the change of logger's license to MIT.

**Comment by philaris** [comment]
I accept the change of logger's license to MIT.

**Comment by stPhena** [comment]
I accept the change of logger's license to MIT.

**Comment by Polkas** [comment]
@daroczig thank you for your contributions, and I am happy to see you more in open source world now:)

I accept the change of logger's license to MIT.

**Comment by kpagacz** [comment]
Nicely done :)

I accept the change of logger's license to MIT.

**Comment by jozefhajnala** [comment]
I accept the change of logger's license to MIT.

**Comment by artemklevtsov** [comment]
I accept the change of logger's license to MIT.

**Comment by deeenes** [comment]
Fine by me! :)

**Comment by averissimo** [comment]
I accept the change of logger's license to MIT.

**Comment by daroczig** [comment]
@amy17519 @earino @terashim could you please provide feedback on the above-mentioned license change?

**Comment by earino** [comment]
I accept the change of logger's license to MIT!

**Comment by daroczig** [comment]
I am planning to release a new version on CRAN in the next week to fix an issue with the recent `glue` package version, so I hope we can resolve this thread before then :) 

@amy17519 and @terashim, could you please kindly report back if you are OK with relicensing `logger` as per above?

**Comment by amy17519** [comment]
I accept the change of logger's license to MIT. Sorry for the delay. Thanks @daroczig, always

**Comment by hadley** [comment]
It looks like @terashim's contribution was 8eb9a6635b98cf9141e6a2ae7abe6ecc6ba1d659, which will be largely replaced by #204.

**Comment by daroczig** [comment]
Yeah, I came to the same conclusion that if we don't hear back in a reasonable time,
we can ~~drop~~revert that commit (basically `formatter_glue_safe`), and reimplement indepent from the original contribution .. but I hope to hear back 😊

**Comment by hadley** [comment]
Yeah, explicit permission is definitely the best option 😄

**Comment by terashim** [comment]
@daroczig Sorry for late. I accept the change of logger's license to MIT.

**Comment by daroczig** [comment]
Yay, thanks so much everyone for your support, and sorry to bother you all with this -- I highly appreciate your kind contributions and the recent help with the relicensing process :bow: :raised_hands: 

We are all set here ... I'll push the related official changes soon.
