### ISSUE TITLE
Other file accessors besides appender?

### ISSUE THREAD

**Issue by eddelbuettel** [daroczig/logger#24]
Maybe I am being dense but while

```r
log_appender(appender_file(someFilename))
```

worked great, I think I'd also like a (trivial)   `create_file(...)` or `overwrite_file()`.  Is there a common idiom in the other logging frameworks?

`logger` is ❤️ though.  Really nice so far.

**Comment by daroczig** [comment]
Sorry, I totally missed this message :scream: 

Can you please clarify on what `create_file` or `overwrite_file` would do?

Currently, `appender_file` will create the file if not existing yet and append a new line for every log message there. Should `overwrite_file` truncate it with each new message?

**Comment by eddelbuettel** [comment]
Yes, I think I was in "debug mode" and wanted an "overwrite, don't append" mode which did not (does not ?) exist yet.  It seems that it is standard POSIX semantics, so should be add a simple "destructive" file accessor?

**Comment by daroczig** [comment]
Thanks for the clarification :+1: 
#29 is a simple workaround for this ... what do you think?

**Comment by eddelbuettel** [comment]
Yes that is close to what I had in mind.  

If it were me I'd also add a convenience function with a different name that just calls this one with `append=FALSE`.    Not sure which (if any) name you'd find most useful.

**Comment by daroczig** [comment]
Yeah, you are right -- I tried to keep the `appender` prefix for all "appender" function names, but there is indeed this case that does not really append ... I guess it's time to give up with that prefix and I will add a helper as suggested above after figuring out the naming bit :)

**Comment by daroczig** [comment]
Okay, so I think this requires dropping the "appender" term from the overall design as well:

![image](https://user-images.githubusercontent.com/495736/61965906-abfcae00-afd1-11e9-9bfd-c407dee99aa5.png)

And the `appender` piece might be renamed to `destination` or something similar. This will require us to rename quite a few pieces .. eg the main `logger` fn will take the current `formatter` and `layout` params  but `destination` instead of `appender` for the last piece, and eg `log_appender` to be renamed to `log_destionation` etc. All these taking functions.

I guess that sounds OK?

I mean the `formatter` piece does sound like something that takes a function, but the `layout` and `destination` are not really ... but that's fine I hope. `appender` in this sense worked better, but as `layout` was already a bit off in this sense (not really suggesting that it's a function), I think `destination` works as well.

Sorry for the wall of text ... but after messing up with the original 3-4 terms on which the whole design was built, probably it's better to spend some extra time to do this right after all.

**Comment by daroczig** [comment]
Referencing the main `logger` to get more clarity on the above: https://github.com/daroczig/logger/blob/master/R/logger.R#L1

**Comment by eddelbuettel** [comment]
Didn't mean to imply cascading changes and wholesale renaming.  `appender_file()` is still fine.  Maybe just add `empty_file()` or `new_file()`  ...

**Comment by daroczig** [comment]
merging now and will generalize the file appender a bit further at #31
