### ISSUE TITLE
Logging stacktrace//escaping glue

### ISSUE THREAD

**Issue by jyoungs** [daroczig/logger#36]
So I'm trying to log the stacktrace from inside `options(error={})` (see: https://stackoverflow.com/questions/1975110/printing-stack-trace-and-continuing-after-error-occurs-in-r)

The problem here is that these strings will often have glue special characters, that then cause additional errors. To get around this, I'm escaping strings before passing them in: 

`escape_glue_syntax <- function(value) { str_replace_all(value, '\\{', '{{') %>% str_replace_all('\\}','}}') }`

This works, but feels pretty nasty- when what I really want is to just not use glue formatting. 

----
Tangentially, I thought maybe I should just call `warning(the_string)` and use `log_warnings()` to capture them into the logger, but despite the reference page (https://daroczig.github.io/logger/reference/log_warnings.html), this doesn't seem to exist?

Any help/advice would be appreciated.

**Comment by daroczig** [comment]
Sorry for the long delay with my reply, just saw this ticket :man_facepalming: 

You can use any other formatter via calling `log_formatter` or you can just wrap the string in `skip_formatter` while passing the stack trace to `logger`. 

Let me know if this helps or I misunderstood the question, otherwise closing.
