### ISSUE TITLE
Status of `appender_dbi`?

### ISSUE THREAD

**Issue by mbacou** [daroczig/logger#47]
Hi,
I read in the vignette:
> And the are many other appender functions bundled with `logger` as well, eg some writing to Syslog, Telegram, Pushbullet, a **database table** or an Amazon Kinesis stream [...]

But looks like appending to a database backend is not available yet? Just curious (main use-case here would be to trigger other database tasks).

Thanks.

**Comment by harrismcgehee** [comment]
https://daroczig.github.io/logger/articles/write_custom_extensions.html#custom-log-record-appenders

This shows how to set up a database appender.  My question is:

If I did set up this appender a package to be used in Shiny apps, how do I close the connection?

I can't figure out how to find the connection object to `pool::poolClose( conn )`

**Comment by daroczig** [comment]
> But looks like appending to a database backend is not available yet?

I don't think it's possible to provide a general solution for that, as appending to a database will require not only setting up the connection, but also the table schema and structure of the log message etc.

But `dbr` can help a lot with that, see eg the example from the above comment at https://daroczig.github.io/logger/articles/write_custom_extensions.html#custom-log-record-appenders

BTW thanks a lot @harrismcgehee for that pointer!

> If I did set up this appender a package to be used in Shiny apps, how do I close the connection?

If that's a concern, I'd rather move the `db_connect` (or the equivalent of your DB helper if using something else than `dbr`) to the `log_appender` function, so that you can close the connection right after the insert.

I hope this helps, please reopen the ticket if you have any ideas on how to improve this.
